export const SEARCH_CONTINENTS = 'SEARCH_CONTINENTS';
export const CLEAR_CONTINENTS = 'CLEAR_CONTINENTS';
export const SELECT_CONTINENT = 'SELECT_CONTINENT';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';
export const DELETE_COUNTRY = 'DELETE_COUNTRY';
export const DELETE_COUNTRIES = 'DELETE_COUNTRIES';
export const OPEN_LIST = 'OPEN_LIST';
export const CLOSE_LIST = 'CLOSE_LIST';